export const VIEW_MLA = "VIEW_MLA";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const UPDATE_ALL_SUMMARIES = "UPDATE_ALL_SUMMARIES";
export const UPDATE_SUMMARY_VIEW = "UPDATE_SUMMARY_VIEW";