export const VIEW_MLA = "VIEW_MLA";
export const UPDATE_ALL_MLAS = "UPDATE_ALL_MLAS";
export const UPDATE_ALL_SUMMARIES = "UPDATE_ALL_SUMMARIES";
export const UPDATE_SUMMARY_FILTER = "UPDATE_SUMMARY_FILTER";
export const UPDATE_SUMMARY_OFFSET = "UPDATE_SUMMARY_OFFSET";