export const FETCH_MLA_PARTICIPATION_BEGIN = "FETCH_MLA_PARTICIPATION_BEGIN";
export const FETCH_MLA_PARTICIPATION_SUCCESS = "FETCH_MLA_PARTICIPATION_SUCCESS";
export const FETCH_MLA_PARTICIPATION_ERROR = "FETCH_MLA_PARTICIPATION_ERROR";
export const FETCH_MLA_PARTICIPATION_ABORT = "FETCH_MLA_PARTICIPATION_ABORT";