export const FETCH_MLA_SUMMARIES_BEGIN = "FETCH_MLA_SUMMARIES_BEGIN";
export const FETCH_MLA_SUMMARIES_SUCCESS = "FETCH_MLA_SUMMARIES_SUCCESS";
export const FETCH_MLA_SUMMARIES_ERROR = "FETCH_MLA_SUMMARIES_ERROR";
export const SET_MLA_SUMMARY_DATE_FILTER = "SET_MLA_SUMMARY_DATE_FILTER";
