export const FETCH_SUMMARIES_BEGIN = 'FETCH_SUMMARIES_BEGIN';
export const FETCH_SUMMARIES_SUCCESS = 'FETCH_SUMMARIES_SUCCESS';
export const FETCH_SUMMARIES_FAILURE = 'FETCH_SUMMARIES_FAILURE';
export const UPDATE_SUMMARY_FILTER = "UPDATE_SUMMARY_FILTER";
export const UPDATE_SUMMARY_OFFSET = "UPDATE_SUMMARY_OFFSET";

export const SET_FIRST_TIME_LOAD = "SET_FIRST_TIME_LOAD";